### ISSUE TITLE
Homebrew: sha1 is deprecated

### ISSUE THREAD

**Issue by frenchja** [icholy/ttygif#58]
In case you're not already aware, I'm logging a ticket about the `ttygif` sha1 warning:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/Users/me/Library/Caches/Homebrew/Formula/ttygif.rb:6:in `<class:Ttygif>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/Users/me/Library/Caches/Homebrew/Formula/ttygif.rb:6:in `<class:Ttygif>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/Users/me/Library/Caches/Homebrew/Formula/ttygif.rb:6:in `<class:Ttygif>'
```

**Comment by icholy** [comment]
I think that's already been updated in master. Which version are you using?

**Comment by frenchja** [comment]
Ah, you're correct.  I hadn't updated in awhile and can't reproduce the issue after fetch and reinstall.  Definitely a user configuration issue.  Closing the ticket.
